### PR TITLE
Remove needless columns from ald_demo

### PR DESCRIPTION
**Pull request by maurolepore**

### CODE REVIEW

**Comment by maurolepore** [comment]
@jdhoffa, please review and merge whenever you are ready.
It passes checks on github actions, locally, and on rhub. In about 3 days from today we are allowed to submit r2dii.data 0.0.4 to CRAN.

**Comment by jdhoffa** [comment]
@maurolepore I will hold off merging this PR until I have more input from @2diiKlaus and @fpalandri 
There seems to be disagreement about what should/ must be included. 
Further, we may also wish to remove `ald_timestamp` and `number_of_assets.

**Comment by maurolepore** [comment]
Ok, thanks for letting me know.

>  we may also wish to remove `ald_timestamp` and `number_of_assets`.

After removing 2 columns I feel the process was more complex than I had expected -- it's easy to miss something. If we ever remove another column, that would suggest we need to capture the process into a checklist or some kind of system, so we can do it faster, safer and with less brain power.

**Comment by jdhoffa** [comment]
Happy to work through this checklist. 
Another point is that perhaps it makes more sense to just leave these columns in... The only harm in doing so would be that it may "confuse" a user, since the demo dataset may have a column that their dataset in practice does not...

**Comment by maurolepore** [comment]
Following a call with @jdhoffa I think we decided to close for now. Leaving the columns seems less harmful than removing them. Instead we may extend the documentation of `ald_demo` to explain some column is generally not available to banks but useful for internal purposes.

**Comment by 2diiKlaus** [comment]
image

The is_ultimate_owner flag needs to be confirmed by @tposey28 as it might be proprietary

**Comment by tposey28** [comment]
Not proprietary, I make it myself!

Taylor

**Comment by maurolepore** [comment]
Added this to my agenda for next time we meet (@jdhoffa, @2diiKlaus and I)

**Comment by maurolepore** [comment]
@2diiKlaus, I think we can soon release a new version on CRAN and I believe this stays out, right?

I feel some uncertainty will remain until we advance the [Discussion on managing and using data](https://github.com/2DegreesInvesting/ds-incubator/issues/35) that we started today. In the meantime it seems prudent to change things as little as possible.

I'll close for now to try keep WIP as low as possible. As usual, feel free to reopen anytime.

**Comment by 2diiKlaus** [comment]
> 
> 
> @2diiKlaus, I think we can soon release a new maintenance version on CRAN and I believe this stays out, right?
> 
> I feel some uncertainty will remain until we advance the [Discussion on managing and using data](https://github.com/2DegreesInvesting/ds-incubator/issues/35) that we started today. In the meantime it seems prudent to change things as little as possible.
> 
> I'll close for now to try keep WIP as low as possible. As usual, feel free to reopen anytime.

@maurolepore I think this is separate from the data discussion. The names need to change and the analysis library needs to work with the new names. I expected it is less work for @jdhoffa  to directly change the column names now and work with the version that aligns with our other workstreams (not bank related-PACTA).

**Comment by maurolepore** [comment]
Thanks @2diiKlaus.
@jdhoffa is it here where you imagine the changes to happen? I believe you suggested changing things downstream instead, via some interface that uses the data as is and converts it to what analyses need? If so please suggest a repo to move this issue.

**Comment by jdhoffa** [comment]
I think this has been resolved by the creation of `r2dii.data::ald_scenario_demo`

**Comment by maurolepore** [comment]
Thanks, I think so too.

**Pull request closed without merging**
