### PR TITLE
nace_ and naics_classification should be different

### PR DESCRIPTION
**Pull request by maurolepore**
* Expose bug

``` r
# These two datasets seem to have always been identical. Here is the result
# at the first commit I found that includes these datasets.
#
# commit c9c1b414ffed91aec3fb3bd2b9d2b18fffb39a73
# Author: Mauro Lepore <maurolepore@gmail.com>
#   Date:   Fri Mar 6 17:42:07 2020 -0600

devtools::load_all()
#> Loading r2dii.data
identical(nace_classification, naics_classification)
#> [1] TRUE
```

<sup>Created on 2020-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by jdhoffa** [comment]
weird, so it turns out that `nace_classiciation.csv` and `naics_classification.csv` are actually correct in `./data-raw/` so the bug occurs somewhere in the data prep.

**Comment by jdhoffa** [comment]
Closes #85

**Comment by jdhoffa** [comment]
@maurolepore is it appropriate to update the NEWS.md after a change like this?

**Comment by jdhoffa** [comment]
I thought of a clever/ simple way to address 2DegreesInvesting/r2dii.match#203 directly in .data, so I added it to this PR. I have identified the related commits, so if you feel it's better to move them to a different PR we can also do that. 

Basically I just added a `manual_classification` dataset that would translate sectors one-to-one to the 2dii sectors. (so if the code_system is MANUAL and the input code is "oil and gas" it gets bridged to "oil and gas"). 

I'm going to add a check in `r2dii.match` as well that ensures that the input code are in the relevant classification file.

**Comment by maurolepore** [comment]
> @maurolepore is it appropriate to update the NEWS.md after a change like this?

Absolutely. Any change that faces the users should have an entry in NEWS.md. I'll review after the ds-incubator today.

**Comment by maurolepore** [comment]
> if you feel it's better to move them to a different PR we can also do that.

Up to you to decide. The way I think about PRs is based on how cleanly I could revert any change. If there is any chance you may want to split the commits later, then two separate PR is best. 
If you find that  adding a PR adds to much overhead, maybe it's time to be friends with the PR helpers of the usethis pacakge -- particularly `usethis::pr_sync()` saves a lot of brainless time.

**Comment by jdhoffa** [comment]
No problem regarding overhead! It's more a worry about conflicting commits (especially annoying in this package with all the binary data files, and data_dictionary getting updated when any new dataset is added). I think it would be best to have two separate PRs, so I will revert those last commits, and then open a new PR after this has been merged

**Pull request merged**
