### PR TITLE
Address CRAN requests towards v0.0.3

### PR DESCRIPTION
**Pull request by maurolepore**
Add man-roxygen/
Add resubmission notes

### CODE REVIEW

**Comment by maurolepore** [comment]
@jdhoffa, do you think the documentation of the generic datasets is useful? Or should we remove it and integrate it into the documentation of specific datasets? For example, 

* [generic](https://2degreesinvesting.github.io/r2dii.data/reference/ald_description.html)
* [specific](https://2degreesinvesting.github.io/r2dii.data/reference/ald_demo.html)

**Comment by maurolepore** [comment]
@jdhoffa, I finished addressing the second of the two problems that CRAN identified. The commits above define each of the columns of each of the datasets -- information that comes via `data_dictionary()`, using the helper #15 

You may see this locally, or in the website -- once we merge into master.

**Comment by jdhoffa** [comment]
I would vote to remove it and integrate it into the individual documentation for each dataset

**Comment by jdhoffa** [comment]
Hey @maurolepore, I read through all of these changes in detail. Made a VERY minor change to the ald_demo description to make it read a little better. 

Do you think these still need more detail?

**Pull request merged**
