### PR TITLE
Source raw data

### LINKED ISSUE #256: Missing targets for regional analysis
Hello everyone,

We have encountered a small data issue when running the PACTA analysis with one bank in Nigeria. We are not getting targets for Africa when using WEO2020 scenarios, but we do when using WEO2019 scenarios.

I provide a full description on the reprex below.

Some alternatives we have considered:
1. WEO 2020 doesn't have Africa - although we have checked already, and it actually has 
2. The bridge file is missing Africa for WEO 2020

Please let us know if there is anything else I should add for context.

Thanks a lot!
Daisy

@georgeharris2deg

```
loanbook <- r2dii.data::loanbook_demo

ald <- r2dii.data::ald_demo

# scenario information directly downloaded from this [link](https://www.transitionmonitor.com/wp-content/uploads/2021/07/WEO-2019-ETP-2017-Fossil-Fuel-Power-Auto.csv)
scenario_weo_2019 <- read_csv("/Users/daisypacheco/Documents/work/banks/2DII_material/scenarios_WEO-2019-ETP-2017-Fossil-Fuel-Power-Auto.csv")

# scenario information directly downloaded from this [link](https://www.transitionmonitor.com/wp-content/uploads/2021/07/WEO-2020-Fossil-Fuel-Power.csv)
scenario_weo_2020 <- read_csv("/Users/daisypacheco/Documents/work/banks/2DII_material/scenarios_WEO-2020-Fossil-Fuel-Power.csv") 

region <- r2dii.data::region_isos

matched <- loanbook %>%
  match_name(ald) %>%
  prioritize()

results_market_share_2019 <- target_market_share(matched, ald, scenario = scenario_weo_2019, region_isos = region)

# I am doing some filtering, so I can show that we do get targets for 2019 but not for 2020
filtering_2019 <- results_market_share_2019 %>% 
  filter(region == "africa") %>% 
  group_by(metric) %>% 
  summarise(total_production = sum(production)) 

results_market_share_2020 <- target_market_share(matched, ald, scenario = scenario_weo_2020, region_isos = region)

filtering_2020 <- results_market_share_2020 %>% 
  filter(region == "africa") %>% 
  group_by(metric) %>% 
  summarise(total_production = sum(production))

```

### PR DESCRIPTION
**Pull request by jdhoffa**
Closes #256

### CODE REVIEW

**Comment by jdhoffa** [comment]
So it seems like #256 is just an issue of us not having had pushed the most recent version of this package to CRAN, however, it is still interesting that running `r2dii.usethis::source_data_raw()` touches 18(!) `.rda` files within the package. 

We should explore this before submitting to CRAN.

**Comment by maurolepore** [comment]
I see some workflows fail but seems unrelated to our code

```
Error: Failed to get R 3.6.3: Failed to get R 3.6.3: Failed to install qpdf: Error: The process 'C:\ProgramData\Chocolatey\bin\choco.exe' failed with exit code 1
```

**Review by maurolepore — APPROVED** [review]
LGTM.

**Comment by maurolepore** [comment]
Yeah, it's curious so many files are updated when we source data-raw/, but if something meaningful had indeed changed I would expect the snapshot tests to fail. I wonder if the few bites that changed in each binary file are only metadata?

**Comment by jdhoffa** [comment]
Ya i imagine you are correct. All of the changes are on the order of a couple of Bytes.

**Pull request merged**
