### PR TITLE
Add hdv to ald_demo

### LINKED ISSUE #231: AR data update: New sectors `hdv` and `aviation`
AR will update the data it provides to include two new sectors `hdv` and `aviation`. `ald_demo` should be updated to reflect these changes.

### PR DESCRIPTION
**Pull request by jdhoffa**
In line with the new AR dataset being released in July, this PR aims to: 
- normalize the existing mock aviation data in `ald_demo`, and express it in a range that is similar to what we would expect
- remove the existing `*_hdv` values for `technologies` within the `automotive` sector
- add a new `hdv` sector, with the same `technologies` as automotive

Add a handful of new "HDV" companies. 

I tried to do this as programmatically as possible, though the code may not be the most intuitive/ beautiful. 

Closes #231

### CODE REVIEW

**Comment by jdhoffa** [comment]
With a couple changes, we can see the `hdv` now outputs from the `target_market_share` function. 
**NOTE: It does not at this stage make sense to add any hdv companies to `loanbook_demo` since NO sector classification codes will link to `hdv`.**

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)
library(r2dii.match)
library(r2dii.analysis)

matched <- loanbook_demo %>% 
  match_name(ald_demo) %>% 
  prioritize() %>% 
  filter(sector_ald == "automotive") %>% 
  mutate(
    name_ald = "scania",
    sector_ald = "hdv"
    )

scenario <- scenario_demo_2020 %>% 
  mutate(sector = "hdv")

target_market_share(
  matched, 
  ald_demo, 
  scenario, 
  region_isos_demo
)
#> # A tibble: 2,840 x 8
#>    sector technology  year region scenario_source metric     production
#>    <chr>  <chr>      <int> <chr>  <chr>           <chr>           <dbl>
#>  1 hdv    electric    2020 global demo_2020       projected      18171.
#>  2 hdv    electric    2020 global demo_2020       target_cps     18171.
#>  3 hdv    electric    2020 global demo_2020       target_sds     18171.
#>  4 hdv    electric    2020 global demo_2020       target_sps     18171.
#>  5 hdv    electric    2021 global demo_2020       projected      20240.
#>  6 hdv    electric    2021 global demo_2020       target_cps     18440.
#>  7 hdv    electric    2021 global demo_2020       target_sds     19799.
#>  8 hdv    electric    2021 global demo_2020       target_sps     18512.
#>  9 hdv    electric    2022 global demo_2020       projected      21803.
#> 10 hdv    electric    2022 global demo_2020       target_cps     18702.
#> # … with 2,830 more rows, and 1 more variable: technology_share <dbl>
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jdhoffa** [comment]
Equally, with some minimal tweaks, `aviation` will output values: 
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)
library(r2dii.match)
library(r2dii.analysis)

matched <- loanbook_demo %>% 
  match_name(ald_demo) %>% 
  prioritize() %>% 
  filter(sector_ald == "aviation")

scenario <- co2_intensity_scenario_demo %>% 
  filter(sector ==  "cement") %>% 
  mutate(sector = "aviation")
  

target_sda(
  matched, 
  ald_demo, 
  scenario,
)
#> Warning: Removing ald rows where `emission_factor` is NA
#> # A tibble: 133 x 4
#>    sector    year emission_factor_metric emission_factor_value
#>    <chr>    <dbl> <chr>                                  <dbl>
#>  1 aviation  2013 projected                          65825190.
#>  2 aviation  2014 projected                          65700760.
#>  3 aviation  2015 projected                          65576330.
#>  4 aviation  2016 projected                          65451899.
#>  5 aviation  2017 projected                          65327469.
#>  6 aviation  2018 projected                          65203038.
#>  7 aviation  2019 projected                          65078608.
#>  8 aviation  2020 projected                          64954178.
#>  9 aviation  2021 projected                          64829747.
#> 10 aviation  2022 projected                          64705317.
#> # … with 123 more rows
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jdhoffa** [comment]
Remaining to be done: 
- Add entires in `loanbook_demo` and `scenario_demo_2020` corresponding to `ldv`

**Comment by jdhoffa** [comment]
@maurolepore from my manual checks, this change DOES cause 1 test to fail on the CRAN release of `r2dii.match`. 
However, it is a `snapshot()` test, which from what I understand is skipped on CRAN (and a brittle test in the first place).

**Comment by maurolepore** [comment]
Thanks for checking. Maybe leave a record of why the snapshot fails in the form of a gh-issue. That should save us time figuring out what's going on.

As per CRAN, we should be safe. I also think that's the behaviour and if there is a reverse dependency issue we should catch it during the process we use to release and also should be catched by CRAN robots on submission.

**Review by maurolepore — APPROVED** [review]
LGTM. I think the meeting we just had mostly replaces my code review.

**Pull request merged**
