### PR TITLE
Updated Kosovo's iso code from "rs" to "xk" (#186)

### LINKED ISSUE #186: iso2c for Kosovo
in [data-raw/iso_codes.csv](https://github.com/2DegreesInvesting/r2dii.data/blob/master/data-raw/iso_codes.csv)
Kosovo has iso2c codes as "rs", so does Serbia. Technically speaking, Kosovo does not have a ISO 3166-1 code. It is common to use "XK" (Unicode CLDR and World Bank), and "XK" falls in the range of allowable user-assigned ISO 3166-1 codes, so it's guaranteed to not conflict with any assigned ISO 3166-1 code. "XK" also appears to be used in our ALD, see 2DegreesInvesting/create_interactive_report/issues/272

### PR DESCRIPTION
**Pull request by jdhoffa**
Updated Kosovo's iso code from "rs" to "xk". 

Closes #186

### CODE REVIEW

**Comment by jdhoffa** [comment]
I'm a bit confused about the failing checks here. 
I think we are comparing a dataset which has changed in this PR (`region_isos`) against the regression value of that dataset as it is on CRAN (and of course this test will fail). 

Am I confused?

**Review by maurolepore — APPROVED** [review]
LGTM

**Comment by maurolepore** [comment]
Not sure what's going on but I'll list my steps here. Hopefully we'll figure this our in retrospective.

1. I checkout your pr locally.
2. I run `source_data_raw()`.
3. I inspect the status and git detects many changes.
4. I run tests and reproduce the error I see on CI.
 ...

**Comment by jdhoffa** [comment]
Oh yup, it was a mistake on my part, I hadn't run `source_data_raw`. Fixing

**Comment by maurolepore** [comment]
It's too easy to forget. Maybe we need to setup a hook or something.

**Comment by jdhoffa** [comment]
Happy to merge?

**Pull request merged**
