### PR TITLE
Switch license to CC0 (appropriate for data)

### LINKED ISSUE #159: Do we need to change the license, again?
https://r-pkgs.org/license.html

image

### PR DESCRIPTION
**Pull request by maurolepore**
Closes #159 

We recently changed the license of this package from GPL-3 to MIT; but instead we should have changed it to CC0 because this package contains mainly data.

image

--

All authors mentioned here,

- [x] @maurolepore 
- [x] @jdhoffa 
- [x] @2diiKlaus 
- [x] 2 Degrees Investing Initiative (contact@2degrees-investing.org)

If you support the change, please write a comment in this thread like this one: 

> I support changing the license of this package to CC0.

### CODE REVIEW

**Comment by maurolepore** [comment]
I support changing the license of this package to CC0.

**Comment by jdhoffa** [comment]
I support changing the license of this package to CC0.

**Comment by maurolepore** [comment]
@2diiKlaus, just a friendly reminder to please support the change to the more appropriate license cc0 by writting

"I support changing the license of this package to CC0"

Sorry for bothering you again with this.

**Comment by 2diiKlaus** [comment]
@jdhoffa @maurolepore I support those changes if you recommend them as I clearly have less knowledge than you!

**Comment by maurolepore** [comment]
This PR has a commit that seems to belong elsewhere: 
3b28544e4f7ca5403d3ae594d8b480dfe35af408. That
commit increments the version number but that was
done already by b66b313899ae5249aef560bd73cbff2df377e35f.
I suspect I pushed this PR from an outdated local master; sorry.

But I'll leave 3b28544e4f7ca5403d3ae594d8b480dfe35af408 here,
as removing it seems not worth the hassle.

**Pull request merged**
