### PR TITLE
New dataset cnb classification (#173)

### LINKED ISSUE #173: Sector Bridge - CNB
More sector classification bridges :) 

This time the CNB - Central Nigerian Bank classification system 

Attached is the bridge 

Note the CNB only gives descriptions, not codes. In this bridge, new codes have been created for the descriptions (original_code) 

Thanks a lot!
George 
[CNB_SECTOR_CLASSIFICATON.xlsx](https://github.com/2DegreesInvesting/r2dii.data/files/5529422/CNB_SECTOR_CLASSIFICATON.xlsx)

### PR DESCRIPTION
**Pull request by jdhoffa**
Package gains new CNB sector classification. 
Closes #173

### CODE REVIEW

**Review by maurolepore — CHANGES_REQUESTED** [review]
FYI I see three merge confilcts. Can you please try fix those?

**Comment by jdhoffa** [comment]
ugh lol, so used to pulling from `origin` since the P2020 stuff! 
I'm up to date with my fork 8-)

fixing now

**Comment by jdhoffa** [comment]
Weird... all tests and checks pass locally for me

**Comment by maurolepore** [comment]
This false positives are becoming problematic enough to do something about it  :)
But I wonder if the problem will go away if we use the snaphsot approach of testthat 3e. So maybe I'll start there -- as I would like to migrate to testthat 3e anyway. Sounds good with you?

**Review by maurolepore — APPROVED** [review]
LGTM.
I run `source_data_raw()` and updateed ref-sector_clasification and now I see all tests pass. 
Thanks!

**Pull request merged**
